_id: "451290900824326144"
name: test1
model: ""
createdAt: 2024-05-30T07:48:55.337Z
updatedAt: 2024-05-30T07:48:55.337Z
createdBy: z1XPm7bpvbpCNCTtneossjSJgGa1jDgY9ik
updatedBy: z1XPm7bpvbpCNCTtneossjSJgGa1jDgY9ik
gitType: simple
temperature: 1
topP: 1
