_id: "451290900824326144"
name: test1
description: this is test1 ahhaha
model: ""
createdAt: 2024-05-30T07:48:55.337Z
updatedAt: 2024-05-30T08:09:26.739Z
createdBy: z1XPm7bpvbpCNCTtneossjSJgGa1jDgY9ik
updatedBy: z1XPm7bpvbpCNCTtneossjSJgGa1jDgY9ik
pinnedAt: null
gitType: default
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
