_id: "451290900824326144"
name: remote
description: null
model: ""
createdAt: 2024-05-30T07:48:55.337Z
updatedAt: 2024-05-30T08:44:08.578Z
createdBy: z1nsEW95t7JA7XXavzgSKwFd2rDqydAFAxA
updatedBy: z1nsEW95t7JA7XXavzgSKwFd2rDqydAFAxA
pinnedAt: null
gitType: default
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
